using System.Text;
using GuardDog.Core.Models;

namespace GuardDog.Core.Diagram;

/// <summary>
/// Iterates through <see cref="SchemaSnapshot.Tables"/> and generates a Mermaid
/// <c>erDiagram</c> showing:
///   • Every table as an entity with its columns and store types
///   • Relationships derived from FK constraints with Crow's Foot notation
///
/// Example output:
/// <code>
/// erDiagram
///     Customers {
///         int Id PK
///         nvarchar(200) Name
///         nvarchar(256) Email
///     }
///     Orders {
///         int Id PK
///         int CustomerId FK
///         datetime2 CreatedAt
///     }
///     Customers ||--o{ Orders : "places"
/// </code>
/// </summary>
public sealed class MermaidErDiagramGenerator : IMermaidGenerator
{
    public string Generate(SchemaSnapshot snapshot)
    {
        var sb = new StringBuilder();

        sb.AppendLine("# Database Schema");
        sb.AppendLine();
        sb.AppendLine($"> Auto-generated by Guard Dog · Snapshot v{snapshot.Version} " +
                      $"· {snapshot.GeneratedAt:yyyy-MM-dd HH:mm} UTC");
        sb.AppendLine();
        sb.AppendLine("```mermaid");
        sb.AppendLine("erDiagram");

        // ── Entity blocks ─────────────────────────────────────────────────────
        foreach (var table in snapshot.Tables.OrderBy(t => t.Name))
        {
            sb.AppendLine($"    {SanitizeName(table.Name)} {{");

            foreach (var col in table.Columns)
            {
                var annotations = new List<string>();
                if (table.PrimaryKeyColumns.Contains(col.Name, StringComparer.OrdinalIgnoreCase))
                    annotations.Add("PK");
                if (table.ForeignKeys.Any(fk => fk.Columns.Contains(col.Name, StringComparer.OrdinalIgnoreCase)))
                    annotations.Add("FK");

                var ann   = annotations.Count > 0 ? $" {string.Join(",", annotations)}" : string.Empty;
                var type  = SanitizeType(col.StoreType);
                var name  = SanitizeName(col.Name);
                var nullable = col.IsNullable ? " \"nullable\"" : string.Empty;

                sb.AppendLine($"        {type} {name}{ann}{nullable}");
            }

            sb.AppendLine("    }");
        }

        sb.AppendLine();

        // ── Relationships (from FK constraints) ───────────────────────────────
        var relationships = new HashSet<string>();

        foreach (var table in snapshot.Tables)
        {
            foreach (var fk in table.ForeignKeys)
            {
                // Determine cardinality:
                //   Principal (1 side) ||--o{ Dependent (many side)
                // We use ||--o{ (one or more) as the standard relationship;
                // adjust to ||--|{ if the FK columns are NOT NULL (mandatory).
                var optional = table.Columns
                    .Where(c => fk.Columns.Contains(c.Name, StringComparer.OrdinalIgnoreCase))
                    .All(c => c.IsNullable);

                var principalCardinality = "||";   // exactly one on principal side
                var dependentCardinality = optional ? "o{" : "|{";  // zero-or-many vs one-or-many

                var rel = $"    {SanitizeName(fk.PrincipalTable)} {principalCardinality}--{dependentCardinality} " +
                          $"{SanitizeName(table.Name)} : \"\"";

                if (relationships.Add(rel))
                    sb.AppendLine(rel);
            }
        }

        sb.AppendLine("```");

        return sb.ToString();
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    /// <summary>
    /// Mermaid identifiers cannot contain spaces, dots, or special chars.
    /// Replace common separators with underscores.
    /// </summary>
    private static string SanitizeName(string name) =>
        name.Replace(" ", "_").Replace("-", "_").Replace(".", "_");

    /// <summary>
    /// Mermaid doesn't support parentheses in type names.
    /// Strip length specifiers for readability: nvarchar(200) → nvarchar.
    /// </summary>
    private static string SanitizeType(string type)
    {
        var paren = type.IndexOf('(');
        return paren >= 0 ? type[..paren] : type;
    }
}
